source 'https://github.com/CocoaPods/Specs.git'


plugin 'cocoapods-art', :sources => [
  'cocoapods-local'
]

platform :ios, '10.0'

use_frameworks!

target 'HungerStation' do
  target 'NotificationService' do
    inherit! :search_paths
  end

  # pods we own
  pod 'TransitionalLoader', :git => 'git@github.com:HungerStation/TransitionalLoader.git'
  pod 'CustomerChat', :git => 'git@github.com:HungerStation/logistics-rider-app-sendbird-ios.git'
  pod 'NUIParse', :git => 'git@github.com:HungerStation/NUIParse.git'

  # mandatory pods that we know
  pod 'Fabric', '1.6.13'
  pod 'Crashlytics', '3.8.6'
  pod 'RestKit', '0.27.2'
  pod 'AFNetworking', '1.3.4'
  pod 'GooglePlaces', '3.1.0'
  pod 'GoogleMaps', '3.1.0'
  pod 'GoogleTagManager'
  pod 'Adjust', '4.18.1'
  pod 'Appboy-iOS-SDK', '3.20.2'
  pod 'NUI', git: 'https://github.com/tombenner/nui.git'
  pod 'ZendeskSDK', '1.9.2.2'
  pod 'CheckoutKit'
  
  # mandatory pods if used
  pod 'GoogleConversionTracking', '3.4.0'
  pod 'Firebase/Analytics', '3.17.0'
  pod 'Firebase/Core', '3.17.0'
  pod 'Firebase/RemoteConfig', '3.17.0'
  pod 'ZDCChat', '1.3.6.1'
  pod 'mopub-ios-sdk', '4.16.1'
  pod 'FunWithFlags', '5.0.8'
  
  # pods we prefer to use instead of creating (they are usefull, good and don't affect or bond with anything else in code)
  pod 'SVProgressHUD', '2.2'
  pod 'IQKeyboardManagerSwift', :git => 'https://github.com/hackiftekhar/IQKeyboardManager.git', :tag => 'v6.5.0'
  pod 'SDWebImage', '5.0.0'
  pod 'SwifterSwift', :git => 'https://github.com/SwifterSwift/SwifterSwift.git', :tag => '5.1.0'
  pod 'Kingfisher', '5.7.1'
  
  # TO-BE REMOVED
  pod 'WYPopoverController', '0.2.2'
  pod 'DYRateView', '0.0.2'
  pod 'PDFReader'
  pod 'NotificationBannerSwift', :git=> 'https://github.com/mmgrt/NotificationBanner.git', :tag => '1.8.9'
  pod 'XLPagerTabStrip', '8.1.0'
  pod 'TWMessageBarManager', '1.8.1'
  pod 'AlignedCollectionViewFlowLayout', '1.1.2'

  #  pod 'CardIO', '5.3.2'
  pod 'UITextView+Placeholder', '1.3.3'

  #  REMOVED ON 24 Sep
  #  pod 'CardIO', '5.3.2'

end

target 'HungerStationTests' do
  
end

target 'HungerStationUITests' do
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_ENABLE_OBJC_GC'] = 'supported' # Disable Warnings for Pods
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
      if target.name == 'PDFReader'
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '4'
          end
      end
    end
  end
end